# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Working/MyS/Sistema_Sumador_IP/Sintesis/sistema_sumador.srcs/sources_1/bd/sistema/ip/sistema_processing_system7_0_0/sistema_processing_system7_0_0.xci
# IP: The module: 'sistema_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Working/MyS/Sistema_Sumador_IP/Sintesis/sistema_sumador.srcs/sources_1/bd/sistema/ip/sistema_processing_system7_0_0/sistema_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Working/MyS/Sistema_Sumador_IP/Sintesis/sistema_sumador.srcs/sources_1/bd/sistema/ip/sistema_processing_system7_0_0/sistema_processing_system7_0_0.xci
# IP: The module: 'sistema_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Working/MyS/Sistema_Sumador_IP/Sintesis/sistema_sumador.srcs/sources_1/bd/sistema/ip/sistema_processing_system7_0_0/sistema_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
